// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABoJMhHJUS9PZOx3QwZQY57y8ufU9jGyw',
    appId: '1:170282732645:web:548feac1d7812fa0994a8c',
    messagingSenderId: '170282732645',
    projectId: 'priv-notes',
    authDomain: 'priv-notes.firebaseapp.com',
    storageBucket: 'priv-notes.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXpXF-u3mVRrNTQfnjNpz0NxNC5f32UnU',
    appId: '1:170282732645:android:fc66ea5cebe2ac3b994a8c',
    messagingSenderId: '170282732645',
    projectId: 'priv-notes',
    storageBucket: 'priv-notes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy82iBARDO33vTsmg1RyRiK8N2dLG2838',
    appId: '1:170282732645:ios:1b4abe9fb7e3b2e7994a8c',
    messagingSenderId: '170282732645',
    projectId: 'priv-notes',
    storageBucket: 'priv-notes.appspot.com',
    iosClientId: '170282732645-6dt228gs3gdspdghf7qe397rv1m0p9vq.apps.googleusercontent.com',
    iosBundleId: 'com.bleh.privnotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy82iBARDO33vTsmg1RyRiK8N2dLG2838',
    appId: '1:170282732645:ios:1b4abe9fb7e3b2e7994a8c',
    messagingSenderId: '170282732645',
    projectId: 'priv-notes',
    storageBucket: 'priv-notes.appspot.com',
    iosClientId: '170282732645-6dt228gs3gdspdghf7qe397rv1m0p9vq.apps.googleusercontent.com',
    iosBundleId: 'com.bleh.privnotes',
  );
}
